### ISSUE TITLE
consider defaulting to longer names for short emails?

### ISSUE THREAD

**Issue by dylanpyle** [koaninc/vanitizer#3]
I noticed when signing up for Koan that we were assigned the domain name `ca.koan.co`. Took me a second to figure out that this was from parsing my email (`d@ca.la`)

No worries at all if i'm a special case and you just want to close this, but may be worth considering using the longer suggestion (`ca-la` in our case) if it hits some set of heuristics - e.g. less than 3 characters, non-gTLD or something.

**Comment by arendn** [comment]
Hi! It's of intended behaviour. Is there an issue with you having the ca.koan.co domain? .ca is short!?

**Comment by dylanpyle** [comment]
Yeah, I think this library is behaving as expected. Probably this more of a product feature request for Koan itself to allow people to change their domain — our name is CALA, so we generally try to use domains like "cala.koan.co".
